# Generated by Django 3.0.6 on 2020-06-03 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filerequest',
            old_name='filePath',
            new_name='fileName',
        ),
    ]
